### ISSUE TITLE
Making the website responsive

### ISSUE THREAD

**Issue by bun137** [bun137/kinto-b.github.io#3]
## About

On a larger screen the website looks really neat but when seen on a smaller screen the text gets squeezed together and isn't readable . You can see this when you inspect the page.
Make the website responsive.

## bounty 25

**Comment by therefat** [comment]
hi @bun137  assign me

**Comment by bun137** [comment]
hey, really sorry, but this issue is to be solved for an internal hacktoberfest event

**Comment by anirudhsudhir** [comment]
Can i work on this issue?

**Comment by bun137** [comment]
yepp assigned

**Comment by bun137** [comment]
@anirudhsudhir please open a pr, its almost 30 mins assignment

**Comment by bun137** [comment]
this pr is open for assignments

**Comment by maverickayush7** [comment]
can i get is assigned ?

**Comment by bun137** [comment]
@maverickayush7 you can start working on, please open a pr before 30 mins of being assigned and lmk your progress

**Comment by bun137** [comment]
by opening a pr, I mean show some progress and not solve the complete issue!

**Comment by harveen-10** [comment]
can i work on this issue?

**Comment by bun137** [comment]
@harveen-10 you can start working on this issue! 
I will unassign @maverickayush7 in few and assign you, eating rn

Please make sure to show some progress in 30 mins and lmk

**Comment by bun137** [comment]
@harveen-10 please open a draft PR to show your progress!

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by bun137** [comment]
@ssether04 you can start working on this issue!

**Comment by bun137** [comment]
do open a draft PR to show your progress!

**Comment by bun137** [comment]
issue resolved!
